### ISSUE TITLE
Cannot send email on web platform

### ISSUE THREAD

**Issue by philipvu30** [kaisellgren/mailer#131]
Hi kaisellgren,

I have followed your example and successfully sent my email, but if only I use it in built-in app. Because my current project is for web development not mobile app, so my question here is "does your package support flutter web app?". I have tried to run this package on chrome and other browsers but none is working.

Thank you and have a nice day :)

**Comment by close2** [comment]
If you create a web application the whole application runs inside the browser.

Applications inside the browser can only use xml-httprequests for communication.
You can not communicate with an SMTP server using xml-httprequests!

To solve your problem:
Either find a mail service provider with a REST API
For instance https://www.socketlabs.com/developers/ (Injection API) or https://sendgrid.com/solutions/smtp-service/  (SMTP API).
Or write your own web service (a normal dart app): Extract the mail sending part.  Run it on a cheap virtual server (should cost you less then 3$ / month).

Please note:  it is _really_ easy to extract username and password from flutter apps.  It doesn't matter if android, web, ...)

I would recommend to write your own web service.
_The web service should control the content and destination mail addresses_
Assume that an attacker can read your code (because they really can) and prevent spammers from using your service.

If you write such a web-service consider open sourcing it.  This question is asked regularly, I would provide a link to your project on the "frontpage".  Feel free to contact me for questions, if you really intend to do that.

**Comment by philipvu30** [comment]
Thank you Christian Loitsch. Have a nice day mate :)
