### ISSUE TITLE
Mailer - Images in Custom Mail is not loading, 

### ISSUE THREAD

**Issue by orcecso** [kaisellgren/mailer#185]
Hi, im a fan of your mailer, which i manage to send emails without any problems, 

but when i now started adding a custom email, with images, logos, etc,

it does not load at all, i tried following other peoples solution from this post : 
https://stackoverflow.com/questions/59447484/local-flutter-asset-image-not-showing-in-html-widget

The logo codes in the html is src="images/image-7.png" and it does not show the image, now following the solution that OP posted,
`<img` src="asset:assets/images/logo_tst.png" `alt="web-img2">`

now its `src="asset:images/image-7.png"`

but still not able to load,
I have attached a picture sample on what i received on my test email,

perhaps if there is no issue, can you give me a guide to try and follow? 
![test](https://user-images.githubusercontent.com/58863067/127616137-d0c6624a-d34a-4132-a70f-f5ca0804ce4f.png)

Another one i noticed is this layout of the code when i inspect the email,
it seems that the src image, either asset or the original html code didnt recognize the picture, 
![Untitled2](https://user-images.githubusercontent.com/58863067/127617333-9eb1669a-5a84-4c94-8269-af356cce7d6d.png)

let me know on what to do and Thanks and long live for you,

**Comment by orcecso** [comment]
May i ask to follow up this?

**Comment by close2** [comment]
@orcecso If you want to embed an image in your mail you have to reference the mail using the `cid` prefix:
```dart
    ..html = '<h1>Test</h1>\n<p>Hey! Here is some HTML content</p><img src="cid:myimg@3.141"/>'
    ..attachments = [
      FileAttachment(File('exploits_of_a_mom.png'))
        ..location = Location.inline
        ..cid = '<myimg@3.141>'
```

Create a unique name for every image you want to display in your html code.  
This name must contain an `@`.

In the example above the name is: `myimg@3.141`

In you html code the `src` attribute can then reference the image using `src="cid:YOUR_UNIQUE_NAME"`

Then attach the image using a `FileAttachment`.  The attachment must have the `location` set to `Location.inline`.
Add the `cid` value but **add `<` and `>` around YOUR_UNIQUE_NAME.

In the example above the `cid` becomes: **`<`**`myimg@3.141`**`>`**


If you send such an html text and for instance the `src` attribute is missing it was probably removed by some server.  Either because it was invalid, or because the mail-service is trying to protect the privacy of its customers.

**Comment by orcecso** [comment]
Hi,

Thanks for updating this, I manage to make a fix by simply uploading the images, logos, etc to websites like imgur, and then add them to the <image src="link here"/>, and it works, i am currently looking for disadvantages of doing this, as putting images of personal stuff on the internet is not a good thing,? :)

although i realize adding the pictures in attachment may sound better than mine,

im still new at this, but i realize of doing this cause img src can link images on the internet, and i thought that google cannot load files offline or local, so it works?

ill try your suggestion once i am finish with my task, hopefully it will work,

thank you for your help,

**Comment by close2** [comment]
There are 2 ways to display images in links:
* embedding the image
* using an external http server.  For instance imgur.

** Embedding the image **
Advantages:
* The chances that your image will be displayed are higher.  A few mail services block images if they are not embedded.
* You can be sure that even if the website goes down, all your mails will still look fine.

** Using an external http server **
Advantages:
* You can reuse the same image for all your mails.  You could even update the image and it will be updated (in some) clients.

If the URL is not guessable and you know that the URLs can't be listed (which is probably only realistic if you have your own server) you can even put personal stuff onto an http server.  It's just a lot more risky.
