### ISSUE TITLE
Mail does not always reach the receiver when using google SMTP server.

### ISSUE THREAD

**Issue by StephanCassel** [kaisellgren/mailer#88]
Hi, 
I'm using gmail smtp server together with mailer plugin. When I using the app it works 100% and sometime for my user but most of the time the mail is stopped and I found a "**A suspected login attempt was prevented**" in the mail inbox. I turned "**Access for less secure apps**" on but it didn't help. 
Is there anyone that can guide me how to use mailer/google smtp correct?
Tons of thanks in advanced.

**Comment by close2** [comment]
I am not completely sure if I understand you correctly.
You were able to send mails using `mailer` by enabling _"Access for less secure apps"_.
This worked only for a short period of time before google decided to block the access.

If this is the case, this is not a `mailer` issue.

It sounds like you distribute an app an try to send mails from different devices (this would trigger google to block your login).

You could switch to dedicated mailing systems.  We for instance use https://www.socketlabs.com/signup/ at our company.

However you have to realize, that it's pretty easy to extract the SMTP login data from an app.  This would allow anybody to send spam in your name.

If your app is for trusted users only (company app,...) then this approach is acceptable.  Otherwise you really should add a small service (rest-webpage) which takes the information and sends an email.
Note that you can write a small rest-service using dart and reuse your code.

Another possibility would be to use the https://pub.dev/packages/flutter_mailer package, which uses the device mail service.  AFAIK this however is a user assisted action.

If there is a problem in the `mailer` package, please reopen.

**Comment by Stephan-Enoro** [comment]
Thanks for reply. Goole SMTP works OK for some users. I have decided to try out MailGun instead.
